language: node_js
node_js:
  - "14.5.0"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build

script:
  - echo "Skipping tests"

notifications:
  email:
    recipients:
      - alexander.katkov.h@icloud.com
    on_success: always # default: change
    on_failure: always # default: always
  webhooks:
    urls:
      - https://api.vercel.com/v1/integrations/deploy/QmcBquWyrCKfyaEy7KnjPZedNRxQQZ9ndz69fti6GCKj42/Z9dhq7Xteh
    on_success: always # default: always

after_script:
  - curl -d '{"chat_id":"-432352018","photo":"https://api.travis-ci.com/7architect/devbuff-frontend.png?token=KpNyjhzrpjT79DwToHzr&branch=develop","parse_mode":"markdown","text":"Devbuff frontend build was finished","caption":"\#build $TRAVIS_BUILD_NUMBER\nFrontend **#$TRAVIS_EVENT_TYPE**\n\n**[🔀 $TRAVIS_COMMIT](https://github.com/7architect/devbuff-frontend/commit/$TRAVIS_COMMIT)**\: *$TRAVIS_COMMIT_MESSAGE*\n**☑️ Tests** $TRAVIS_TEST_RESULT","reply_markup":{"inline_keyboard":[[{"text":"🔀 View commit","url":"https://github.com/7architect/devbuff-frontend/commit/$TRAVIS_COMMIT"},{"text":"🕜 View job","url":"http://example.com/$TRAVIS_JOB_WEB_URL"}]]}}'  -H "Content-Type: application/json" -X POST https://api.telegram.org/bot1259459324:AAHBXPj3C1hUIpWKnPK6aPKOiahgky6INVM/sendPhoto
