version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14.15.4'
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - telegram/status
orbs:
  telegram: uniqueck/telegram-orb@0.0.1
