version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - telegram/status
orbs:
  telegram: uniqueck/telegram-orb@0.0.1
